# Generated by Django 3.1.3 on 2020-11-28 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(4)])),
                ('credit', models.IntegerField(blank=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.student')),
                ('managers', models.ManyToManyField(related_name='Estudiante', to='profesores.Teacher')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['code'],
            },
        ),
    ]
